### ISSUE TITLE
New Component - Pagination

### ISSUE THREAD

**Issue by langdonx** [IdanCo/ng1bs4#28]
I might be able to take a crack at it if you're accepting PRs.

References:
- Pagination in Bootstrap 4: https://v4-alpha.getbootstrap.com/components/pagination/
- Pagination in UI Bootstrap: https://angular-ui.github.io/bootstrap/#!#pagination
    - It has absolutely no styling with Bootstrap 4 CSS

PS: You've been making some great progress here!  Keep it up!

**Comment by IdanCo** [comment]
Sure! That'll be great, let me know if there's anything you need!

thank :-)
