### ISSUE TITLE
Add Development instructions to README.md

### ISSUE THREAD

**Issue by langdonx** [IdanCo/ng1bs4#32]
#### Instructions for getting started

1. Install Node.js 6.x
1. Fork the repository
1. Clone the forked repository
1. Run the following commands
    1. `npm i`
    1. `npm run serve`
1. Open http://localhost:8080 in a browser

#### Instructions for after you've switched branches or merged from upstream

1. Run the following commands
    1. `npm prune`
    1. `npm i`
    1. `npm run serve`

**Comment by langdonx** [comment]
It could simplify things if there was a `start` script in package.json.  I think this is what a lot of folks are doing these days?

`{ "start": "npm run build && npm run serve" }`

Also, is there a way to get `WebpackDevServer` to open the browser for us?

**Comment by IdanCo** [comment]
Go for it!

actually the 'build' part is not necessary for development, so i think you can simply switch 'serve' with 'start', no?

**Comment by langdonx** [comment]
Haha, I'm not sure, this was partly me asking about the workflow and partly me trying help others with it.

I thought I ran into an error trying just serve, but I deleted `dist/` and `/docs` and ran it again and it seems OK.
