### ISSUE TITLE
Upgrade to Bootstrap v4.0.0-beta

### ISSUE THREAD

**Issue by pripatelUK** [IdanCo/ng1bs4#60]
[Bootstrap 4 Beta](https://github.com/twbs/bootstrap/releases) was released today, ng1bs4 is currently not building correctly as package.json automatically updates to the latest bootstrap version. 

Peer Dependencies: jquery and popper.js are both required for Bootstrap 4 beta.

**Comment by IdanCo** [comment]
thanks, on it!
